import type { TemplateId, TemplateManifest } from '../types'
import { defaultDesign } from '../brand/midnightDesign'
import { CoverHook, DividerClosing, ImageText, ListInsight, MidnightQuote, QuoteBasic, QuoteCommentary } from '../templates/templates'
const variants = [{ id: 'default', label: '기본', tone: 'dark' as const }]
export const templateRegistry: Record<TemplateId, TemplateManifest> = {
  'cover-hook': { id:'cover-hook', name:'강한 표지', description:'첫 장 표지', variants, defaultVariant:'default', fields:[{key:'kicker',label:'작은 제목',type:'text',maxLength:40},{key:'title',label:'메인 제목',type:'textarea',maxLength:120},{key:'subtitle',label:'보조 문장',type:'textarea',maxLength:160}], fontRange:{title:{min:54,max:100}}, sampleContent:{content:{kicker:'NEW PERSPECTIVE',title:'생각을 바꾸는\n[[한 문장]]',subtitle:'오늘의 관점을 한 장에 담아보세요.'}}, component:CoverHook },
  'midnight-quote': { id:'midnight-quote', name:'미드나이트 문장', description:'한 장 문장 카드', variants, defaultVariant:'default', fields:[{key:'kicker',label:'작은 제목',type:'text',maxLength:40},{key:'body',label:'본문',type:'textarea',maxLength:500},{key:'source',label:'출처·이름',type:'text',maxLength:80},{key:'note',label:'하단 문구',type:'text',maxLength:120}], fontRange:{body:{min:40,max:84}}, sampleContent:{content:{kicker:'오늘의 한 문장',body:'서두르지 않아도 괜찮습니다.\n[[꾸준함]]은 결국 방향을 만듭니다.',source:'하건',note:'오늘의 생각을 기록합니다.'}}, component:MidnightQuote, defaultDesign, capabilities:['backgroundColor','textColor','fontId','fontSize','letterSpacing','showPageNumber'] },
  'quote-basic': { id:'quote-basic', name:'기본 인용', description:'짧은 인용과 출처', variants, defaultVariant:'default', fields:[{key:'quote',label:'인용문',type:'textarea',maxLength:260},{key:'source',label:'출처',type:'text',maxLength:80},{key:'description',label:'설명',type:'textarea',maxLength:200}], fontRange:{quote:{min:44,max:76}}, sampleContent:{content:{quote:'좋은 질문은 새로운 길을 엽니다.',source:'오늘의 기록',description:'답보다 질문을 오래 품어보세요.'}}, component:QuoteBasic },
  'list-insight': { id:'list-insight', name:'인사이트 목록', description:'번호가 있는 요약', variants, defaultVariant:'default', fields:[{key:'title',label:'제목',type:'text',maxLength:100},{key:'items',label:'목록 (줄마다 한 항목)',type:'list',maxLength:300},{key:'closing',label:'마무리',type:'text',maxLength:120}], fontRange:{title:{min:48,max:80}}, sampleContent:{content:{title:'일을 가볍게 만드는 [[세 가지]] 습관',items:['오늘 할 일을 세 개만 고르기','완벽보다 완료를 선택하기','끝난 일을 기록하기'],closing:'작은 반복이 큰 차이를 만듭니다.'}}, component:ListInsight },
  'quote-commentary': { id:'quote-commentary', name:'인용과 해설', description:'문장과 해설의 조합', variants, defaultVariant:'default', fields:[{key:'quote',label:'인용문',type:'textarea',maxLength:200},{key:'commentary',label:'해설',type:'textarea',maxLength:320},{key:'source',label:'출처',type:'text',maxLength:80}], fontRange:{quote:{min:40,max:68}}, sampleContent:{content:{quote:'기록은 생각을 눈앞에 꺼내 놓는 일이다.',commentary:'적어야 비로소 무엇을 알고 무엇을 모르는지 선명해집니다.',source:'작업 노트'}}, component:QuoteCommentary },
  'image-text': { id:'image-text', name:'사진과 글', description:'사진 위주의 이야기', variants, defaultVariant:'default', fields:[{key:'image',label:'배경 이미지',type:'image'},{key:'title',label:'제목',type:'text',maxLength:100},{key:'body',label:'본문',type:'textarea',maxLength:300},{key:'caption',label:'캡션',type:'text',maxLength:120}], fontRange:{title:{min:44,max:76}}, sampleContent:{content:{title:'한 장면에서 시작된 이야기',body:'사진과 함께 기억하고 싶은 내용을 적어보세요.',caption:'PHOTO NOTE'}}, component:ImageText },
  'divider-closing': { id:'divider-closing', name:'구분·마무리', description:'섹션 전환과 마지막 장', variants, defaultVariant:'default', fields:[{key:'kicker',label:'작은 제목',type:'text',maxLength:40},{key:'title',label:'메인 문장',type:'textarea',maxLength:180},{key:'cta',label:'행동 요청',type:'text',maxLength:120}], fontRange:{title:{min:48,max:88}}, sampleContent:{content:{kicker:'ONE MORE THING',title:'오늘 배운 것을\n[[한 번]] 실천해보세요.',cta:'저장하고 천천히 다시 읽어보세요.'}}, component:DividerClosing },
}
export const templateList = Object.values(templateRegistry)
