import { createDesign } from '../brand/cardDesign'
import type { DesignCapability, LayoutControl, TemplateId, TemplateManifest } from '../types'
import {
  Comparison,
  CoverHook,
  DividerClosing,
  ImageText,
  ListInsight,
  MidnightQuote,
  ProcessSteps,
  QuoteBasic,
  QuoteCommentary,
  StatHighlight,
} from '../templates/templates'

const variants = [{ id: 'default', label: '기본', tone: 'dark' as const }]
const commonCapabilities: DesignCapability[] = [
  'backgroundColor',
  'textColor',
  'gradient',
  'fontId',
  'letterSpacing',
  'lineHeight',
  'showPageNumber',
]
const withLayout = (...controls: LayoutControl[]) => controls
const darkDesign = (overrides = {}) => createDesign({
  backgroundColor: '#141C33',
  textColor: '#FFFFFF',
  ...overrides,
})
const lightDesign = (overrides = {}) => createDesign({
  backgroundColor: '#F7EFE1',
  textColor: '#172033',
  ...overrides,
})

export const templateRegistry: Record<TemplateId, TemplateManifest> = {
  'cover-hook': {
    id: 'cover-hook',
    name: '임팩트 표지',
    description: '첫 장 표지',
    variants,
    defaultVariant: 'default',
    fields: [
      { key: 'kicker', label: '작은 제목', type: 'text', maxLength: 40 },
      { key: 'title', label: '메인 제목', type: 'textarea', maxLength: 120 },
      { key: 'subtitle', label: '보조 문장', type: 'textarea', maxLength: 160 },
    ],
    fontRange: { title: { min: 54, max: 110 } },
    sampleContent: { content: { kicker: 'NEW PERSPECTIVE', title: '생각을 바꾸는\n[[한 문장]]', subtitle: '오늘의 관점을 한 장에 담아보세요.' } },
    component: CoverHook,
    defaultDesign: darkDesign({ fontSize: 92, secondaryFontSize: 34, lineHeight: 1.25, textAlign: 'left', verticalAlign: 'center', contentWidth: 88 }),
    capabilities: [...commonCapabilities, 'textAlign', 'verticalAlign', 'contentWidth'],
    layoutControls: withLayout(
      { key: 'fontSize', label: '제목 크기', min: 54, max: 110, step: 2, unit: 'px' },
      { key: 'secondaryFontSize', label: '보조 문장 크기', min: 22, max: 48, step: 2, unit: 'px' },
    ),
  },
  'midnight-quote': {
    id: 'midnight-quote',
    name: '문장 카드',
    description: '한 장 문장 카드',
    variants,
    defaultVariant: 'default',
    fields: [
      { key: 'kicker', label: '작은 제목', type: 'text', maxLength: 40 },
      { key: 'body', label: '본문', type: 'textarea', maxLength: 500 },
      { key: 'source', label: '출처·이름', type: 'text', maxLength: 80 },
      { key: 'note', label: '하단 문구', type: 'text', maxLength: 120 },
    ],
    fontRange: { body: { min: 40, max: 84 } },
    sampleContent: { content: { kicker: '오늘의 한 문장', body: '서두르지 않아도 괜찮습니다.\n[[꾸준함]]은 결국 방향을 만듭니다.', source: '하건', note: '오늘의 생각을 기록합니다.' } },
    component: MidnightQuote,
    defaultDesign: darkDesign({ fontSize: 62, lineHeight: 1.55, textAlign: 'center', verticalAlign: 'center', contentWidth: 100 }),
    capabilities: [...commonCapabilities, 'textAlign', 'verticalAlign', 'contentWidth'],
    layoutControls: withLayout(
      { key: 'fontSize', label: '본문 크기', min: 40, max: 84, step: 2, unit: 'px' },
    ),
  },
  'quote-basic': {
    id: 'quote-basic',
    name: '기본 인용',
    description: '짧은 인용과 출처',
    variants,
    defaultVariant: 'default',
    fields: [
      { key: 'quote', label: '인용문', type: 'textarea', maxLength: 260 },
      { key: 'source', label: '출처', type: 'text', maxLength: 80 },
      { key: 'description', label: '설명', type: 'textarea', maxLength: 200 },
    ],
    fontRange: { quote: { min: 44, max: 84 } },
    sampleContent: { content: { quote: '좋은 질문은 새로운 길을 엽니다.', source: '오늘의 기록', description: '답보다 질문을 오래 품어보세요.' } },
    component: QuoteBasic,
    defaultDesign: lightDesign({ fontSize: 68, secondaryFontSize: 30, lineHeight: 1.45, textAlign: 'left', contentWidth: 100 }),
    capabilities: [...commonCapabilities, 'textAlign', 'contentWidth'],
    layoutControls: withLayout(
      { key: 'fontSize', label: '인용문 크기', min: 44, max: 84, step: 2, unit: 'px' },
      { key: 'secondaryFontSize', label: '설명 크기', min: 22, max: 42, step: 2, unit: 'px' },
    ),
  },
  'stat-highlight': {
    id: 'stat-highlight',
    name: '핵심 수치',
    description: '핵심 수치와 의미를 강하게 전달',
    variants,
    defaultVariant: 'default',
    fields: [
      { key: 'kicker', label: '분류', type: 'text', maxLength: 40 },
      { key: 'value', label: '핵심 숫자', type: 'text', maxLength: 16 },
      { key: 'unit', label: '단위', type: 'text', maxLength: 20 },
      { key: 'title', label: '수치의 의미', type: 'textarea', maxLength: 120 },
      { key: 'description', label: '근거·설명', type: 'textarea', maxLength: 240 },
    ],
    fontRange: { value: { min: 120, max: 260 }, title: { min: 42, max: 72 } },
    sampleContent: { content: { kicker: 'KEY NUMBER', value: '68', unit: '%', title: '작은 개선을 매일 반복한 팀의 [[완료율]]', description: '한 번의 큰 변화보다 명확한 우선순위와 짧은 피드백 주기가 성과를 만들었습니다.' } },
    component: StatHighlight,
    defaultDesign: darkDesign({ fontSize: 230, secondaryFontSize: 58, lineHeight: 1.28, textAlign: 'left', verticalAlign: 'center', contentWidth: 90 }),
    capabilities: [...commonCapabilities, 'textAlign', 'verticalAlign', 'contentWidth'],
    layoutControls: withLayout(
      { key: 'fontSize', label: '핵심 숫자 크기', min: 120, max: 260, step: 4, unit: 'px' },
      { key: 'secondaryFontSize', label: '제목 크기', min: 42, max: 72, step: 2, unit: 'px' },
    ),
  },
  'list-insight': {
    id: 'list-insight',
    name: '핵심 인사이트',
    description: '번호가 있는 요약',
    variants,
    defaultVariant: 'default',
    fields: [
      { key: 'title', label: '제목', type: 'text', maxLength: 100 },
      { key: 'items', label: '목록 (줄마다 한 항목)', type: 'list', maxLength: 300 },
      { key: 'closing', label: '마무리', type: 'text', maxLength: 120 },
    ],
    fontRange: { title: { min: 48, max: 82 } },
    sampleContent: { content: { title: '일을 가볍게 만드는 [[세 가지]] 습관', items: ['오늘 할 일을 세 개만 고르기', '완벽보다 완료를 선택하기', '끝난 일을 기록하기'], closing: '작은 반복이 큰 차이를 만듭니다.' } },
    component: ListInsight,
    defaultDesign: lightDesign({ fontSize: 64, secondaryFontSize: 29, spacing: 22, lineHeight: 1.42 }),
    capabilities: commonCapabilities,
    layoutControls: withLayout(
      { key: 'fontSize', label: '제목 크기', min: 48, max: 82, step: 2, unit: 'px' },
      { key: 'secondaryFontSize', label: '목록 글자 크기', min: 22, max: 38, step: 1, unit: 'px' },
      { key: 'spacing', label: '목록 간격', min: 8, max: 40, step: 2, unit: 'px' },
    ),
  },
  'process-steps': {
    id: 'process-steps',
    name: '단계별 가이드',
    description: '순서와 진행 과정을 명확하게 정리',
    variants,
    defaultVariant: 'default',
    fields: [
      { key: 'kicker', label: '분류', type: 'text', maxLength: 40 },
      { key: 'title', label: '제목', type: 'textarea', maxLength: 110 },
      { key: 'items', label: '단계 (줄마다 한 항목)', type: 'list', maxLength: 360 },
      { key: 'closing', label: '마무리', type: 'text', maxLength: 140 },
    ],
    fontRange: { title: { min: 46, max: 78 } },
    sampleContent: { content: { kicker: 'HOW IT WORKS', title: '아이디어를 결과로 바꾸는 [[네 단계]]', items: ['문제를 한 문장으로 정의합니다', '가장 작은 실행 단위를 고릅니다', '빠르게 만들고 직접 확인합니다', '배운 내용을 다음 시도에 반영합니다'], closing: '좋은 과정은 다음 행동을 분명하게 만듭니다.' } },
    component: ProcessSteps,
    defaultDesign: lightDesign({ backgroundColor: '#F5F0E6', fontSize: 64, secondaryFontSize: 30, spacing: 132, lineHeight: 1.42 }),
    capabilities: commonCapabilities,
    layoutControls: withLayout(
      { key: 'fontSize', label: '제목 크기', min: 46, max: 78, step: 2, unit: 'px' },
      { key: 'secondaryFontSize', label: '단계 글자 크기', min: 22, max: 38, step: 1, unit: 'px' },
      { key: 'spacing', label: '단계 행 높이', min: 92, max: 180, step: 4, unit: 'px' },
    ),
  },
  'comparison': {
    id: 'comparison',
    name: '비교 분석',
    description: '두 선택지의 차이를 한눈에 비교',
    variants,
    defaultVariant: 'default',
    fields: [
      { key: 'kicker', label: '분류', type: 'text', maxLength: 40 },
      { key: 'title', label: '제목', type: 'textarea', maxLength: 110 },
      { key: 'leftTitle', label: '왼쪽 제목', type: 'text', maxLength: 40 },
      { key: 'leftItems', label: '왼쪽 항목', type: 'list', maxLength: 240 },
      { key: 'rightTitle', label: '오른쪽 제목', type: 'text', maxLength: 40 },
      { key: 'rightItems', label: '오른쪽 항목', type: 'list', maxLength: 240 },
      { key: 'conclusion', label: '결론', type: 'textarea', maxLength: 160 },
    ],
    fontRange: { title: { min: 44, max: 76 } },
    sampleContent: { content: { kicker: 'BEFORE / AFTER', title: '같은 시간, 다른 [[일의 방식]]', leftTitle: '흐릿한 실행', leftItems: ['모든 일을 동시에 시작', '완성 전에 방향을 잃음', '결과만 보고 회고'], rightTitle: '선명한 실행', rightItems: ['중요한 한 가지부터 시작', '짧게 확인하며 방향 수정', '과정을 기록하고 반복'], conclusion: '속도보다 중요한 것은 다음 판단을 쉽게 만드는 구조입니다.' } },
    component: Comparison,
    defaultDesign: lightDesign({ fontSize: 62, secondaryFontSize: 26, layoutRatio: 50, lineHeight: 1.45 }),
    capabilities: commonCapabilities,
    layoutControls: withLayout(
      { key: 'fontSize', label: '제목 크기', min: 44, max: 76, step: 2, unit: 'px' },
      { key: 'secondaryFontSize', label: '항목 글자 크기', min: 20, max: 34, step: 1, unit: 'px' },
      { key: 'layoutRatio', label: '왼쪽 영역 비율', min: 35, max: 65, step: 5, unit: '%' },
    ),
  },
  'quote-commentary': {
    id: 'quote-commentary',
    name: '인용·해설',
    description: '문장과 해설의 조합',
    variants,
    defaultVariant: 'default',
    fields: [
      { key: 'quote', label: '인용문', type: 'textarea', maxLength: 200 },
      { key: 'commentary', label: '해설', type: 'textarea', maxLength: 320 },
      { key: 'source', label: '출처', type: 'text', maxLength: 80 },
    ],
    fontRange: { quote: { min: 40, max: 72 } },
    sampleContent: { content: { quote: '기록은 생각을 눈앞에 꺼내 놓는 일이다.', commentary: '적어야 비로소 무엇을 알고 무엇을 모르는지 선명해집니다.', source: '작업 노트' } },
    component: QuoteCommentary,
    defaultDesign: darkDesign({ fontSize: 54, secondaryFontSize: 36, layoutRatio: 42, lineHeight: 1.5, textAlign: 'center' }),
    capabilities: [...commonCapabilities, 'textAlign'],
    layoutControls: withLayout(
      { key: 'fontSize', label: '인용문 크기', min: 40, max: 72, step: 2, unit: 'px' },
      { key: 'secondaryFontSize', label: '해설 크기', min: 26, max: 48, step: 2, unit: 'px' },
      { key: 'layoutRatio', label: '인용 영역 높이', min: 32, max: 58, step: 2, unit: '%' },
    ),
  },
  'image-text': {
    id: 'image-text',
    name: '이미지 스토리',
    description: '사진 위주의 이야기',
    variants,
    defaultVariant: 'default',
    fields: [
      { key: 'image', label: '배경 이미지', type: 'image' },
      { key: 'title', label: '제목', type: 'text', maxLength: 100 },
      { key: 'body', label: '본문', type: 'textarea', maxLength: 300 },
      { key: 'caption', label: '캡션', type: 'text', maxLength: 120 },
    ],
    fontRange: { title: { min: 44, max: 76 } },
    sampleContent: { content: { title: '한 장면에서 시작된 이야기', body: '사진과 함께 기억하고 싶은 내용을 적어보세요.', caption: 'PHOTO NOTE' } },
    component: ImageText,
    defaultDesign: lightDesign({ backgroundColor: '#F5F0E6', fontSize: 58, secondaryFontSize: 29, layoutRatio: 50, lineHeight: 1.55 }),
    capabilities: commonCapabilities,
    layoutControls: withLayout(
      { key: 'fontSize', label: '제목 크기', min: 44, max: 76, step: 2, unit: 'px' },
      { key: 'secondaryFontSize', label: '본문 크기', min: 22, max: 38, step: 1, unit: 'px' },
      { key: 'layoutRatio', label: '이미지 영역 높이', min: 35, max: 68, step: 2, unit: '%' },
    ),
  },
  'divider-closing': {
    id: 'divider-closing',
    name: '마무리 카드',
    description: '섹션 전환과 마지막 장',
    variants,
    defaultVariant: 'default',
    fields: [
      { key: 'kicker', label: '작은 제목', type: 'text', maxLength: 40 },
      { key: 'title', label: '메인 문장', type: 'textarea', maxLength: 180 },
      { key: 'cta', label: '행동 요청', type: 'text', maxLength: 120 },
    ],
    fontRange: { title: { min: 48, max: 96 } },
    sampleContent: { content: { kicker: 'ONE MORE THING', title: '오늘 배운 것을\n[[한 번]] 실천해보세요.', cta: '저장하고 천천히 다시 읽어보세요.' } },
    component: DividerClosing,
    defaultDesign: darkDesign({ fontSize: 76, secondaryFontSize: 28, lineHeight: 1.35, textAlign: 'left', verticalAlign: 'center', contentWidth: 88 }),
    capabilities: [...commonCapabilities, 'textAlign', 'verticalAlign', 'contentWidth'],
    layoutControls: withLayout(
      { key: 'fontSize', label: '제목 크기', min: 48, max: 96, step: 2, unit: 'px' },
      { key: 'secondaryFontSize', label: '행동 문구 크기', min: 20, max: 40, step: 2, unit: 'px' },
    ),
  },
}

export const templateList = Object.values(templateRegistry).filter((template) => template.id !== 'quote-basic')
