import { useRef, useState } from 'react'
import { fontFamilies, fontIds, normalizeDesign } from '../brand/midnightDesign'
import { DEFAULT_OVERLAY_IMAGE } from '../engine/overlayImage'
import { imageFileToDataUrl } from '../engine/imageTools'
import { templateList, templateRegistry } from '../registry/templateRegistry'
import type { CardPage, TemplateId } from '../types'
interface Props { page: CardPage; onChange:(patch:Partial<CardPage>)=>void; onTemplateChange:(id:TemplateId)=>void }
export function FieldEditor({page,onChange,onTemplateChange}:Props){
 const manifest=templateRegistry[page.templateId]; const overlayInput=useRef<HTMLInputElement>(null); const imageInput=useRef<HTMLInputElement>(null); const [error,setError]=useState('')
 const updateContent=(key:string,value:string|string[])=>onChange({content:{...page.content,[key]:value}})
 const upload=async(file:File|undefined,overlay:boolean)=>{if(!file)return;try{setError('');const src=await imageFileToDataUrl(file);if(overlay)onChange({overlayImage:{src,...DEFAULT_OVERLAY_IMAGE}});else onChange({image:src})}catch(e){setError(e instanceof Error?e.message:'이미지 처리 실패')}}
 const d=normalizeDesign(page.design)
 return <div className="field-editor">
  <label>템플릿<select aria-label="템플릿" aria-describedby="template-description" value={page.templateId} onChange={e=>onTemplateChange(e.target.value as TemplateId)}>{templateList.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
  <p className="muted" id="template-description">{manifest.description}</p>
  {manifest.fields.map(field=>field.type==='image'?<div className="field-group" key={field.key}><span>{field.label}</span><input ref={imageInput} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0],false)}/><button onClick={()=>imageInput.current?.click()}>{page.image?'이미지 교체':'이미지 선택'}</button>{page.image&&<button className="subtle" onClick={()=>onChange({image:null})}>삭제</button>}</div>:<label key={field.key}>{field.label}{field.type==='textarea'?<textarea value={String(page.content[field.key]??'')} maxLength={field.maxLength} onChange={e=>updateContent(field.key,e.target.value)}/>:field.type==='list'?<textarea value={(page.content[field.key] as string[]??[]).join('\n')} maxLength={field.maxLength} onChange={e=>updateContent(field.key,e.target.value.split('\n').slice(0,5))}/>:<input value={String(page.content[field.key]??'')} maxLength={field.maxLength} onChange={e=>updateContent(field.key,e.target.value)}/>} {field.maxLength&&<small>{String(page.content[field.key]??'').length} / {field.maxLength}</small>}</label>)}
  {manifest.capabilities&&<section className="control-section"><h3>디자인 설정</h3>{manifest.capabilities.includes('backgroundColor')&&<label>배경색<div className="color-row"><input type="color" value={d.backgroundColor} onChange={e=>onChange({design:{...d,backgroundColor:e.target.value.toUpperCase()}})}/><input aria-label="배경색 코드" value={d.backgroundColor} pattern="#[0-9A-Fa-f]{6}" onChange={e=>{if(/^#[0-9A-Fa-f]{6}$/.test(e.target.value))onChange({design:{...d,backgroundColor:e.target.value}})}}/></div></label>}{manifest.capabilities.includes('textColor')&&<label>글자색<div className="color-row"><input type="color" value={d.textColor} onChange={e=>onChange({design:{...d,textColor:e.target.value.toUpperCase()}})}/><input aria-label="글자색 코드" value={d.textColor} onChange={e=>{if(/^#[0-9A-Fa-f]{6}$/.test(e.target.value))onChange({design:{...d,textColor:e.target.value}})}}/></div></label>}{manifest.capabilities.includes('fontId')&&<label>글꼴<select value={d.fontId} onChange={e=>onChange({design:{...d,fontId:e.target.value as keyof typeof fontFamilies}})}>{fontIds.map(id=><option key={id} value={id}>{id}</option>)}</select></label>}{manifest.capabilities.includes('fontSize')&&<label>본문 크기 {d.fontSize}px<input type="range" min="40" max="84" step="2" value={d.fontSize} onChange={e=>onChange({design:{...d,fontSize:Number(e.target.value)}})}/></label>}{manifest.capabilities.includes('letterSpacing')&&<label>자간 {d.letterSpacing}%<input type="range" min="-6" max="8" step="0.5" value={d.letterSpacing} onChange={e=>onChange({design:{...d,letterSpacing:Number(e.target.value)}})}/></label>}{manifest.capabilities.includes('showPageNumber')&&<label className="check"><input type="checkbox" checked={d.showPageNumber} onChange={e=>onChange({design:{...d,showPageNumber:e.target.checked}})}/>페이지 번호 표시</label>}</section>}
  <section className="control-section"><h3>떠있는 이미지</h3><input ref={overlayInput} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0],true)}/><div className="button-row"><button onClick={()=>overlayInput.current?.click()}>{page.overlayImage?'이미지 교체':'이미지 선택'}</button>{page.overlayImage&&<button className="danger" onClick={()=>onChange({overlayImage:null})}>삭제</button>}</div>{page.overlayImage&&<><img className="overlay-thumb" src={page.overlayImage.src} alt="떠있는 이미지 미리보기"/><label>너비 {page.overlayImage.width}%<input type="range" min="12" max="100" value={page.overlayImage.width} onChange={e=>onChange({overlayImage:{...page.overlayImage!,width:Number(e.target.value)}})}/></label><label>가로 위치 {page.overlayImage.x}%<input type="range" min="0" max="100" value={page.overlayImage.x} onChange={e=>onChange({overlayImage:{...page.overlayImage!,x:Number(e.target.value)}})}/></label><label>세로 위치 {page.overlayImage.y}%<input type="range" min="0" max="100" value={page.overlayImage.y} onChange={e=>onChange({overlayImage:{...page.overlayImage!,y:Number(e.target.value)}})}/></label><button className="subtle" onClick={()=>onChange({overlayImage:{...page.overlayImage!,...DEFAULT_OVERLAY_IMAGE}})}>크기·위치 가운데로 초기화</button></>}</section>
  {error&&<p className="error" role="alert">{error} 이미지 파일을 다시 선택해 주세요.</p>}
 </div>
}
